Repository RezaRahemtola/42sh, pull requests merged in 2022-05, with the labels that each got.

#3 Automated tests for minishell2
  .github/workflows/main.yml
  tests/tester.py
Labels: enhancement

#11 [FIX] Fixed unit tests
  src/command/execution.c
Labels: bug

#12 Functional tester refactored
  tests/tester.py
Labels: enhancement

#13 [FIX] Wrong error message for corrupted file
  include/messages.h
  src/command/errors.c
  src/command/executor.c
  tests/config.json
  tests/test_minishell.c
Labels: bug

#15 [ADD] Added command state
  Makefile
  include/builtin.h
  include/minishell.h
  include/types.h
  include/varenv.h
  src/builtin/home.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/command/execution.c
  src/command/parsing.c
  src/util/pidlists.c
  src/varenv/variables.c
  tests/test_builtin.c
Labels: enhancement

#19 Makefile refactored (#16)
  .github/workflows/main.yml
  .gitignore
  Makefile
Labels: enhancement

#26 Functional tester to display only the needed stream with diff
  tests/tester.py
Labels: enhancement

#27 Makefile refactored and diff in functional tester
  .github/workflows/main.yml
  .gitignore
  Makefile
  tests/tester.py
Labels: enhancement

#29 Real checks in functional tests
  tests/config.json
Labels: enhancement

#31 << redirection
  include/builtin.h
  include/environment.h
  include/redirections.h
  include/shell.h
  include/types.h
  src/builtin/builtin.c
  src/builtin/directories.c
  src/builtin/home.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/command/execution.c
  src/command/executor.c
  src/command/input.c
  src/command/output.c
  src/command/parsing.c
  src/command/paths.c
  src/command/redirections.c
  src/environment/environment.c
  src/environment/environment_utils.c
  src/environment/variables.c
  src/redirection/files.c
  src/redirection/pipes.c
  src/util/lists.c
  src/util/splitter.c
  src/util/strings.c
  src/utils/lists.c
  src/utils/strings.c
  tests/test_builtin.c
  tests/test_redirections.c
  tests/test_shell.c
  unit_tests
Labels: enhancement

#35 Cleaner tests output
  Makefile
Labels: enhancement

#33 [ADD] && / || operators
  Makefile
  include/logical.h
  include/types.h
  src/builtin/silent.c
  src/command/execution.c
  src/command/logical.c
  src/command/parsing.c
  src/utils/logical.c
  src/utils/redirections.c
  tests/config.json
  tests/info/not_tested.txt
  tests/test_shell.c
  tests/tester.py
Labels: enhancement

#34 Memory checker
  .github/workflows/main.yml
  .gitignore
  Makefile
  src/environment/variables.c
  tests/memory_checker.py
Labels: enhancement

#39 Combining `&&` / `||`
  include/logical.h
  lib/my/src/string/my_strsplit.c
  lib/my/src/string/my_strsplit_many.c
  src/command/execution.c
  src/command/logical.c
  src/command/parsing.c
  src/utils/logical.c
  src/utils/redirections.c
  tests/config.json
Labels: bug

#37 Mandatory separators `&&` and `||` + Memory checker
  .github/workflows/main.yml
  .gitignore
  Makefile
  include/logical.h
  include/types.h
  lib/my/src/string/my_strsplit.c
  lib/my/src/string/my_strsplit_many.c
  src/builtin/silent.c
  src/command/execution.c
  src/command/logical.c
  src/command/parsing.c
  src/environment/variables.c
  src/utils/logical.c
  src/utils/redirections.c
  tests/config.json
  tests/info/not_tested.txt
  tests/memory_checker.py
  tests/test_shell.c
  tests/tester.py
Labels: enhancement

#44 Exit return values fixed
  Makefile
  src/command/execution.c
  tests/config.json
  tests/subject/tester.sh
  tests/subject/tests
  tests/tester.py
Labels: bug

#47 Coding style and tests fixed
  Makefile
  include/shell.h
  lib/my/Makefile
  lib/my/include/my_string.h
  lib/my/src/string/my_substr.c
  src/builtin/home.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/command/execution.c
  src/command/parsing.c
  src/command/paths.c
  src/environment/environment.c
  src/environment/variables.c
  src/utils/logical.c
  src/utils/redirections.c
  tests/config.json
  tests/src/test_builtin.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
  tests/tester.py
Labels: bug

#55 Local env
  Makefile
  include/history.h
  lib/my/Makefile
  lib/my/include/my_string.h
  lib/my/src/list/my_list_add.c
  lib/my/src/list/my_list_operations.c
  lib/my/src/list/my_list_remove.c
  lib/my/src/string/my_strsplit_many.c
  lib/my/src/string/my_timestr.c
  src/builtin/builtin.c
  src/builtin/history.c
  src/builtin/silent_dirs.c
  src/command/parsing.c
  src/environment/environment.c
  src/environment/variables.c
  src/shell.c
  src/utils/history/add.c
  src/utils/history/history.c
  src/utils/history/interact.c
  src/utils/history/save.c
  src/utils/history/substitutions.c
  tests/tester.py
Labels: enhancement

#59 History
  .github/workflows/main.yml
  Makefile
  include/builtin.h
  include/history.h
  include/types.h
  lib/my/Makefile
  lib/my/include/my.h
  lib/my/include/my_list.h
  lib/my/include/my_math.h
  lib/my/include/my_string.h
  lib/my/src/array/my_arrays.c
  lib/my/src/list/my_list_add.c
  lib/my/src/list/my_list_operations.c
  lib/my/src/list/my_list_remove.c
  lib/my/src/math/my_getnbr.c
  lib/my/src/math/my_is_number.c
  lib/my/src/string/my_str_checks.c
  lib/my/src/string/my_str_contains.c
  lib/my/src/string/my_str_starts.c
  lib/my/src/string/my_strsplit_many.c
  lib/my/src/string/my_timestr.c
  src/builtin/builtin.c
  src/builtin/history.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/command/parsing.c
  src/command/paths.c
  src/environment/environment.c
  src/environment/variables.c
  src/shell.c
  src/utils/history/add.c
  src/utils/history/history.c
  src/utils/history/interact.c
  src/utils/history/save.c
  src/utils/history/substitutions.c
  src/utils/logical.c
  src/utils/redirections.c
  tests/config.json
  tests/src/test_builtin.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
  tests/tester.py
Labels: enhancement

#56 Simple set and unset for local env
  Makefile
  include/builtin.h
  include/environment.h
  include/history.h
  include/messages.h
  include/redirections.h
  include/shell.h
  include/types.h
  lib/my/include/my_string.h
  lib/my/src/string/my_timestr.c
  src/builtin/builtin.c
  src/builtin/directories.c
  src/builtin/history.c
  src/builtin/home.c
  src/builtin/localenv.c
  src/builtin/silent.c
  src/command/execution.c
  src/command/executor.c
  src/command/logical.c
  src/command/parsing.c
  src/command/redirections.c
  src/environment/environment.c
  src/environment/environment_utils.c
  src/environment/local/localenv.c
  src/environment/local/localenv_utils.c
  src/environment/local/localenv_variables.c
  src/environment/variables.c
  src/shell.c
  src/utils/history/save.c
  src/utils/lists.c
  tests/config.json
  tests/src/test_builtin.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
Labels: enhancement

#60 Added aliases
  Makefile
  include/builtin.h
  include/shell.h
  include/types.h
  src/builtin/alias.c
  src/builtin/unalias.c
  src/command/parsing.c
  src/shell.c
  src/utils/replacements.c
  src/utils/strings.c
  tests/src/test_builtin.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
Labels: enhancement

#61 Local env set and unset, aliases
  Makefile
  include/builtin.h
  include/environment.h
  include/history.h
  include/messages.h
  include/redirections.h
  include/shell.h
  include/types.h
  lib/my/include/my_string.h
  lib/my/src/string/my_timestr.c
  src/builtin/alias.c
  src/builtin/builtin.c
  src/builtin/directories.c
  src/builtin/history.c
  src/builtin/home.c
  src/builtin/localenv.c
  src/builtin/silent.c
  src/builtin/unalias.c
  src/command/execution.c
  src/command/executor.c
  src/command/logical.c
  src/command/parsing.c
  src/command/redirections.c
  src/environment/environment.c
  src/environment/environment_utils.c
  src/environment/local/localenv.c
  src/environment/local/localenv_utils.c
  src/environment/local/localenv_variables.c
  src/environment/variables.c
  src/shell.c
  src/utils/history/save.c
  src/utils/lists.c
  src/utils/replacements.c
  src/utils/strings.c
  tests/config.json
  tests/src/builtin/tests_alias.c
  tests/src/builtin/tests_cd.c
  tests/src/builtin/tests_env.c
  tests/src/builtin/tests_exit.c
  tests/src/separators/tests_and.c
  tests/src/separators/tests_or.c
  tests/src/separators/tests_semicolon.c
  tests/src/test_builtin.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
Labels: enhancement

#64 Advanced localenv
  Makefile
  include/environment.h
  src/builtin/localenv.c
  src/environment/local/localenv_load.c
  src/environment/local/localenv_utils.c
  src/environment/local/localset_checks.c
  src/shell.c
  tests/config.json
Labels: enhancement

#67 add: Added $ and $? printing
  Makefile
  include/builtin.h
  include/shell.h
  include/types.h
  src/command/execution.c
  src/command/executor.c
  src/command/parsing.c
  src/utils/home.c
  src/utils/lists.c
  src/utils/replacements.c
  src/utils/tests.c
  src/utils/variables.c
  tests/config.json
  tests/src/test_shell.c
Labels: enhancement

#66 Advanced local env and special variables
  Makefile
  include/builtin.h
  include/environment.h
  include/shell.h
  include/types.h
  src/builtin/localenv.c
  src/command/execution.c
  src/command/executor.c
  src/command/parsing.c
  src/environment/local/localenv_load.c
  src/environment/local/localenv_utils.c
  src/environment/local/localset_checks.c
  src/environment/variables.c
  src/shell.c
  src/utils/history/interact.c
  src/utils/home.c
  src/utils/lists.c
  src/utils/prompt.c
  src/utils/replacements.c
  src/utils/tests.c
  src/utils/variables.c
  tests/config.json
  tests/src/builtin/tests_alias.c
  tests/src/builtin/tests_env.c
  tests/src/builtin/tests_history.c
  tests/src/builtin/tests_localenv.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
Labels: bug, enhancement

#69 [ADD] Added norm checker and norm actions
  .github/workflows/main.yml
  .gitignore
  Makefile
  src/utils/tests.c
  tests/info/not_tested.txt
  tests/norm/checks.py
  tests/norm/config.json
  tests/norm/style.py
Labels: enhancement

#70 add: Norm checker and style on CI
  .github/workflows/main.yml
  .gitignore
  Makefile
  src/utils/tests.c
  tests/info/not_tested.txt
  tests/norm/checks.py
  tests/norm/config.json
  tests/norm/style.py
Labels: enhancement

#72 fix: Fixed builtin logical
  src/command/execution.c
  tests/config.json
  tests/src/separators/tests_semicolon.c
Labels: bug

#75 Bug fixes: Operators and builtin, wrong tests.
  src/command/execution.c
  tests/config.json
  tests/src/separators/tests_semicolon.c
Labels: bug

#74 Advanced localvar preload
  include/shell.h
  src/builtin/builtin.c
  src/builtin/home.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/environment/local/localenv_load.c
Labels: enhancement

#78 fix: Set all messages in messages.h
  Makefile
  include/messages.h
  include/shell.h
  src/builtin/alias.c
  src/builtin/builtin.c
  src/builtin/directories.c
  src/builtin/home.c
  src/builtin/localenv.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/builtin/unalias.c
  src/command/errors.c
  src/command/execution.c
  src/command/executor.c
  src/command/input.c
  src/command/output.c
  src/command/parsing.c
  src/command/paths.c
  src/command/redirections.c
  src/environment/environment.c
  src/environment/environment_utils.c
  src/environment/local/localenv.c
  src/environment/local/localenv_load.c
  src/environment/local/localenv_variables.c
  src/environment/local/localset_checks.c
  src/environment/variables.c
  src/redirection/files.c
  src/redirection/pipes.c
  src/shell.c
  src/utils/history/add.c
  src/utils/history/save.c
  src/utils/history/substitutions.c
  src/utils/home.c
  src/utils/lists.c
  src/utils/prompt.c
  src/utils/redirections.c
  src/utils/strings.c
  tests/src/builtin/tests_cd.c
Labels: enhancement

#77 Special localvar, tests and messages refactored
  Makefile
  include/messages.h
  include/shell.h
  src/builtin/alias.c
  src/builtin/builtin.c
  src/builtin/directories.c
  src/builtin/home.c
  src/builtin/localenv.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/builtin/unalias.c
  src/command/errors.c
  src/command/execution.c
  src/command/executor.c
  src/command/input.c
  src/command/output.c
  src/command/parsing.c
  src/command/paths.c
  src/command/redirections.c
  src/environment/environment.c
  src/environment/environment_utils.c
  src/environment/local/localenv.c
  src/environment/local/localenv_load.c
  src/environment/local/localenv_variables.c
  src/environment/local/localset_checks.c
  src/environment/variables.c
  src/redirection/files.c
  src/redirection/pipes.c
  src/shell.c
  src/utils/history/add.c
  src/utils/history/save.c
  src/utils/history/substitutions.c
  src/utils/home.c
  src/utils/lists.c
  src/utils/prompt.c
  src/utils/redirections.c
  src/utils/strings.c
  tests/config.json
  tests/src/builtin/tests_cd.c
Labels: enhancement

#82 Fix/wrong home
  include/shell.h
  src/builtin/builtin.c
  src/builtin/home.c
  src/utils/home.c
  src/utils/startup.c
Labels: bug

#79 add: .42shrc
  Makefile
  include/builtin.h
  include/messages.h
  include/shell.h
  src/builtin/builtin.c
  src/builtin/home.c
  src/shell.c
  src/utils/home.c
  src/utils/replacements.c
  src/utils/startup.c
  src/utils/tests.c
  src/utils/variables.c
  tests/config.json
Labels: enhancement

#84 [FIX] Status relaying on pipes
  Makefile
  include/shell.h
  src/command/execution.c
  src/utils/status.c
  tests/config.json
Labels: bug

#81 Other advanced special variables and aliases
  include/builtin.h
  include/environment.h
  include/logical.h
  include/shell.h
  lib/my/Makefile
  lib/my/include/my.h
  lib/my/include/my_list.h
  lib/my/include/my_string.h
  lib/my/src/array/my_arrays.c
  lib/my/src/list/my_list_add.c
  lib/my/src/list/my_list_operations.c
  lib/my/src/list/my_list_remove.c
  lib/my/src/math/my_is_number.c
  lib/my/src/my_free.c
  lib/my/src/string/my_revstr.c
  lib/my/src/string/my_strrep.c
  lib/my/src/string/my_strsplit.c
  lib/my/src/string/my_strsplit_many.c
  lib/my/src/string/my_substr.c
  src/builtin/builtin.c
  src/builtin/directories.c
  src/builtin/home.c
  src/builtin/silent.c
  src/builtin/silent_dirs.c
  src/command/executor.c
  src/command/logical.c
  src/command/parsing.c
  src/command/signal.c
  src/environment/environment.c
  src/environment/environment_utils.c
  src/environment/local/localenv_load.c
  src/main.c
  src/shell.c
  src/utils/home.c
  src/utils/prompt.c
  src/utils/replacements.c
  src/utils/startup.c
  src/utils/tests.c
  src/utils/variables.c
  tests/src/test_shell.c
Labels: bug, enhancement

#89 Functional tests splitted and enriched
  Makefile
  tests/config.json
  tests/functional/src/builtin/tests_alias.json
  tests/functional/src/builtin/tests_cd.json
  tests/functional/src/builtin/tests_env.json
  tests/functional/src/builtin/tests_exit.json
  tests/functional/src/builtin/tests_localenv.json
  tests/functional/src/config.json
  tests/functional/src/errors.json
  tests/functional/src/separators/tests_and.json
  tests/functional/src/separators/tests_or.json
  tests/functional/src/separators/tests_semicolon.json
  tests/functional/src/tests_complex.json
  tests/functional/src/tests_pipes.json
  tests/functional/src/tests_redirections.json
  tests/functional/src/variables/tests_preload.json
  tests/functional/src/variables/tests_tilde.json
  tests/functional/src/variables/tests_variables.json
  tests/functional/tester.py
  tests/memory_checker.py
Labels: enhancement

#88 add: Added graphics and line edition
  Makefile
  include/graphics.h
  include/messages.h
  include/types.h
  src/shell.c
  src/utils/graphics/arrows.c
  src/utils/graphics/init.c
  src/utils/graphics/input.c
  src/utils/graphics/lines.c
  src/utils/graphics/operations.c
  src/utils/prompt.c
  tests/src/builtin/tests_alias.c
  tests/src/builtin/tests_cd.c
  tests/src/builtin/tests_env.c
  tests/src/builtin/tests_exit.c
  tests/src/builtin/tests_history.c
  tests/src/builtin/tests_localenv.c
  tests/src/separators/tests_and.c
  tests/src/separators/tests_or.c
  tests/src/separators/tests_semicolon.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
Labels: enhancement, help wanted

#87 Advanced history features
  include/history.h
  include/messages.h
  lib/my/include/my_math.h
  lib/my/src/math/my_is_number.c
  src/builtin/history.c
  src/builtin/home.c
  src/command/paths.c
  src/command/redirections.c
  src/environment/local/localenv_load.c
  src/environment/variables.c
  src/utils/history/history.c
  src/utils/history/interact.c
  src/utils/history/save.c
  src/utils/history/substitutions.c
  tests/src/builtin/tests_history.c
Labels: enhancement

#58 Job control
  Makefile
  include/builtin.h
  include/jobs.h
  include/types.h
  src/command/execution.c
  src/command/parsing.c
  src/command/signal.c
  src/job_control/builtin_job.c
  src/job_control/handle_job.c
  src/job_control/remove_job.c
  src/job_control/silent_job.c
  src/shell.c
  tests/src/builtin/tests_alias.c
  tests/src/builtin/tests_cd.c
  tests/src/builtin/tests_env.c
  tests/src/builtin/tests_exit.c
  tests/src/builtin/tests_history.c
  tests/src/builtin/tests_localenv.c
  tests/src/separators/tests_and.c
  tests/src/separators/tests_or.c
  tests/src/separators/tests_semicolon.c
  tests/src/test_redirections.c
  tests/src/test_shell.c
Labels: enhancement

#86 README features
  README.md
Labels: documentation

#92 Feature/custom prompt
  src/command/signal.c
  src/utils/graphics/lines.c
  src/utils/prompt.c
Labels: enhancement

#93 Last fixes
  README.md
  src/command/signal.c
  src/job_control/builtin_job.c
  src/utils/graphics/lines.c
  src/utils/prompt.c
  tests/src/builtin/tests_history.c
Labels: bug, enhancement

#95 Coding style fixes
  include/graphics.h
  lib/my/Makefile
  lib/my/include/my_list.h
  lib/my/src/list/my_list_operations.c
  src/job_control/builtin_job.c
  src/job_control/handle_job.c
  src/utils/graphics/arrows.c
  src/utils/graphics/input.c
  src/utils/prompt.c
  src/utils/tests.c
Labels: bug
